version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version
  - cinst docker-compose

build_script:
  - docker-compose -f docker-compose.development-windows.yml build

test_script:
  - docker-compose -f docker-compose.development-windows.yml up