version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version

build_script:
  - docker --version
  - docker-compose --version  
  - docker-compose -f docker-compose.development.yml build 