version: "3.6"
services:
    app:
        build: src/app
        restart: always
        networks:       
          - wafnetwork
networks:
  wafnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
