version: "3.6"
services:
    waf:
        build: waf
        restart: always
        depends_on: 
         - app-windows
        ports:
            - "127.0.0.1:81:80"
        networks:
            - wafnetwork
    app-windows:
        build: app-windows
        restart: always
        networks:       
          - wafnetwork
networks:
  wafnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
